### ISSUE TITLE
Getting the error ```Error: Timeout reached```

### ISSUE THREAD

**Issue by yasirfaheem** [KK-Designs/UpdateHub#116]
Getting the error ```Error: Timeout reached
    at C:\Users\faheemy\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:808619```.

**Comment by KK-Designs** [comment]
What version of UpdateHub are you using? You can check in the settings page and scroll down to "About"

**Comment by yasirfaheem** [comment]
> What version of UpdateHub are you using? You can check in the settings page and scroll down to "About"
I have versions -

App version - 2.1.0

Chrome version - 114.0.5735.243

Node version - 18.15.0

Electron version - 25.3.1

Os version - 19045.3086

**Comment by KK-Designs** [comment]
Can you send a log file so we can better see what's happening? It is located at C:\Users\USERNAME\AppData\Roaming\update-hub\app.log. Upload that file here, and we can try to fix the error faster.

**Comment by yasirfaheem** [comment]
[7/27/2023 1:22:56 PM]: Load event: index.html (at preload.js:1:337418)
[7/27/2023 1:25:04 PM]: Load event: settings.html (at preload.js:1:337418)
[7/27/2023 1:25:27 PM]: Load event: osupdate.html (at preload.js:1:337418)
[7/27/2023 1:25:27 PM]: Load event: osupdate.html (at preload.js:1:337418)

[7/27/2023 1:25:27 PM]: Testing internet speed, please wait... (at preload.js:1:612068)
[7/27/2023 1:25:27 PM]: Load event: osupdate.html (at preload.js:1:337418)

[7/27/2023 1:25:27 PM]: Testing internet speed, please wait... (at preload.js:1:612068)

[7/27/2023 1:25:27 PM]: Internet speed is 31.56 Mbps (at preload.js:1:611044)
[7/27/2023 1:29:48 PM]: Load event: settings.html (at preload.js:1:337418)
[7/27/2023 1:29:50 PM]: Load event: osupdate.html (at preload.js:1:337418)
[7/27/2023 1:29:50 PM]: Load event: osupdate.html (at preload.js:1:337418)

[7/27/2023 1:29:50 PM]: Testing internet speed, please wait... (at preload.js:1:612068)
[7/27/2023 1:29:50 PM]: Load event: osupdate.html (at preload.js:1:337418)

[7/27/2023 1:29:50 PM]: Testing internet speed, please wait... (at preload.js:1:612068)

[7/27/2023 1:29:51 PM]: Internet speed is 56.68 Mbps (at preload.js:1:611044)
[7/27/2023 1:29:53 PM]: Load event: settings.html (at preload.js:1:337418)
[7/27/2023 1:30:13 PM]: Load event: msstore.html (at preload.js:1:337418)
[7/27/2023 1:30:13 PM]: Load event: msstore.html (at preload.js:1:337418)

[7/27/2023 1:30:13 PM]: Testing internet speed, please wait... (at preload.js:1:612068)
[7/27/2023 1:30:13 PM]: Load event: msstore.html (at preload.js:1:337418)

[7/27/2023 1:30:13 PM]: Testing internet speed, please wait... (at preload.js:1:612068)

[7/27/2023 1:30:14 PM]: Internet speed is 77.15 Mbps (at preload.js:1:611044)
[7/27/2023 1:30:17 PM]: Load event: settings.html (at preload.js:1:337418)
[7/27/2023 1:30:23 PM]: Load event: index.html (at preload.js:1:337418)
[7/27/2023 1:30:28 PM]: Load event: apps.html (at preload.js:1:337418)
[7/27/2023 1:30:28 PM]: Load event: apps.html (at preload.js:1:337418)

[7/27/2023 1:30:28 PM]: Testing internet speed, please wait... (at preload.js:1:612068)
[7/27/2023 1:30:28 PM]: Load event: apps.html (at preload.js:1:337418)

[7/27/2023 1:30:28 PM]: Testing internet speed, please wait... (at preload.js:1:612068)

[7/27/2023 1:30:30 PM]: Internet speed is 14.43 Mbps (at preload.js:1:611044)
[7/27/2023 1:30:28 PM]: Load event: apps.html (at preload.js:1:337418)

[7/27/2023 1:30:28 PM]: Testing internet speed, please wait... (at preload.js:1:612068)

[7/27/2023 1:30:30 PM]: Internet speed is 14.43 Mbps (at preload.js:1:611044)

[7/27/2023 1:30:31 PM]: Checking for updates... (at preload.js:1:810623)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
[7/27/2023 1:32:11 PM]: Error: Timeout reached
    at C:\Users\faheemy\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:808619 (at preload.js:1:936343)
[7/27/2023 1:36:44 PM]: Load event: settings.html (at preload.js:1:337418)
[7/27/2023 1:36:56 PM]: Load event: index.html (at preload.js:1:337418)
[7/27/2023 1:37:03 PM]: Load event: osupdate.html (at preload.js:1:337418)
[7/27/2023 1:37:03 PM]: Load event: osupdate.html (at preload.js:1:337418)

[7/27/2023 1:37:03 PM]: Testing internet speed, please wait... (at preload.js:1:612068)
[7/27/2023 1:37:03 PM]: Load event: osupdate.html (at preload.js:1:337418)

[7/27/2023 1:37:03 PM]: Testing internet speed, please wait... (at preload.js:1:612068)

[7/27/2023 1:37:03 PM]: Internet speed is 24.77 Mbps (at preload.js:1:611044)
[7/27/2023 1:37:06 PM]: Load event: index.html (at preload.js:1:337418)
[7/27/2023 1:49:39 PM]: Load event: index.html (at preload.js:1:337418)
[7/27/2023 1:49:44 PM]: Load event: osupdate.html (at preload.js:1:337418)
[7/27/2023 1:49:44 PM]: Load event: osupdate.html (at preload.js:1:337418)

[7/27/2023 1:49:44 PM]: Testing internet speed, please wait... (at preload.js:1:612068)
[7/27/2023 1:49:44 PM]: Load event: osupdate.html (at preload.js:1:337418)

[7/27/2023 1:49:44 PM]: Testing internet speed, please wait... (at preload.js:1:612068)

[7/27/2023 1:49:45 PM]: Internet speed is 35.94 Mbps (at preload.js:1:611044)
[7/27/2023 1:49:44 PM]: Load event: osupdate.html (at preload.js:1:337418)

[7/27/2023 1:49:44 PM]: Testing internet speed, please wait... (at preload.js:1:612068)

[7/27/2023 1:49:45 PM]: Internet speed is 35.94 Mbps (at preload.js:1:611044)

[7/27/2023 1:50:38 PM]: child process exited with code 0 (at preload.js:1:913712)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[7/27/2023 1:49:44 PM]: Load event: osupdate.html (at preload.js:1:337418)

[7/27/2023 1:49:44 PM]: Testing internet speed, please wait... (at preload.js:1:612068)

[7/27/2023 1:49:45 PM]: Internet speed is 35.94 Mbps (at preload.js:1:611044)

[7/27/2023 1:50:38 PM]: child process exited with code 0 (at preload.js:1:913712)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)

[7/27/2023 1:50:38 PM]: 2 Updates available (at preload.js:1:916754)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[7/27/2023 1:51:25 PM]: Load event: msstore.html (at preload.js:1:337418)
[7/27/2023 1:51:25 PM]: Load event: msstore.html (at preload.js:1:337418)

[7/27/2023 1:51:25 PM]: Testing internet speed, please wait... (at preload.js:1:612068)
[7/27/2023 1:51:25 PM]: Load event: msstore.html (at preload.js:1:337418)

[7/27/2023 1:51:25 PM]: Testing internet speed, please wait... (at preload.js:1:612068)

[7/27/2023 1:51:25 PM]: Internet speed is 37.17 Mbps (at preload.js:1:611044)
[7/27/2023 1:51:35 PM]: Load event: index.html (at preload.js:1:337418)
[7/27/2023 1:51:41 PM]: Load event: apps.html (at preload.js:1:337418)
[7/27/2023 1:51:41 PM]: Load event: apps.html (at preload.js:1:337418)

[7/27/2023 1:51:41 PM]: Testing internet speed, please wait... (at preload.js:1:612068)
[7/27/2023 1:51:41 PM]: Load event: apps.html (at preload.js:1:337418)

[7/27/2023 1:51:41 PM]: Testing internet speed, please wait... (at preload.js:1:612068)

[7/27/2023 1:51:43 PM]: Internet speed is 13.63 Mbps (at preload.js:1:611044)
[7/27/2023 1:51:41 PM]: Load event: apps.html (at preload.js:1:337418)

[7/27/2023 1:51:41 PM]: Testing internet speed, please wait... (at preload.js:1:612068)

[7/27/2023 1:51:43 PM]: Internet speed is 13.63 Mbps (at preload.js:1:611044)

[7/27/2023 1:51:43 PM]: Checking for updates... (at preload.js:1:810623)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
[7/27/2023 1:53:24 PM]: Error: Timeout reached
    at C:\Users\faheemy\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:808619 (at preload.js:1:936343)
[7/27/2023 1:51:41 PM]: Load event: apps.html (at preload.js:1:337418)

[7/27/2023 1:51:41 PM]: Testing internet speed, please wait... (at preload.js:1:612068)

[7/27/2023 1:51:43 PM]: Internet speed is 13.63 Mbps (at preload.js:1:611044)

[7/27/2023 1:51:43 PM]: Checking for updates... (at preload.js:1:810623)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

[7/27/2023 3:29:10 PM]: {} (at preload.js:1:589032)
    at FSWatcher.emit (node:events:513:28)
    at FSWatcher._handle.onchange (node:internal/fs/watchers:215:12)
[7/27/2023 1:53:24 PM]: Error: Timeout reached
    at C:\Users\faheemy\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:808619 (at preload.js:1:936343)

[7/27/2023 3:29:12 PM]: TypeError: Cannot read properties of undefined (reading 'replace')
    at escapeRegExp (C:\Users\faheemy\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:122617)
    at C:\Users\faheemy\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:589408
    at Array.filter (<anonymous>)
    at FSWatcher.<anonymous> (C:\Users\faheemy\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:589385)
    at FSWatcher.emit (node:events:513:28)
    at FSWatcher._handle.onchange (node:internal/fs/watchers:215:12) (at preload.js:1:936343)
[7/27/2023 1:53:24 PM]: Error: Timeout reached
    at C:\Users\faheemy\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:808619 (at preload.js:1:936343)

[7/27/2023 3:29:12 PM]: TypeError: Cannot read properties of undefined (reading 'replace')
    at escapeRegExp (C:\Users\faheemy\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:122617)
    at C:\Users\faheemy\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:589408
    at Array.filter (<anonymous>)
    at FSWatcher.<anonymous> (C:\Users\faheemy\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:589385)
    at FSWatcher.emit (node:events:513:28)
    at FSWatcher._handle.onchange (node:internal/fs/watchers:215:12) (at preload.js:1:936343)

[7/27/2023 3:29:41 PM]: Failed to send error report (at preload.js:1:4487
[7/27/2023 6:55:37 PM]: Load event: index.html (at preload.js:1:337418)
[7/27/2023 6:55:57 PM]: Load event: index.html (at preload.js:1:337418)
[7/27/2023 6:56:20 PM]: Load event: apps.html (at preload.js:1:337418)
[7/27/2023 6:56:20 PM]: Load event: apps.html (at preload.js:1:337418)

[7/27/2023 6:56:20 PM]: Testing internet speed, please wait... (at preload.js:1:612068)
[7/27/2023 6:56:20 PM]: Load event: apps.html (at preload.js:1:337418)

[7/27/2023 6:56:20 PM]: Testing internet speed, please wait... (at preload.js:1:612068)

[7/27/2023 6:56:21 PM]: Internet speed is 13.78 Mbps (at preload.js:1:611044)
[7/27/2023 6:56:20 PM]: Load event: apps.html (at preload.js:1:337418)

[7/27/2023 6:56:20 PM]: Testing internet speed, please wait... (at preload.js:1:612068)

[7/27/2023 6:56:21 PM]: Internet speed is 13.78 Mbps (at preload.js:1:611044)

[7/27/2023 6:56:22 PM]: Checking for updates... (at preload.js:1:810623)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
[7/27/2023 6:58:05 PM]: Error: Timeout reached
    at C:\Users\faheemy\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:808619 (at preload.js:1:936343)
[7/28/2023 10:32:44 PM]: Load event: index.html (at preload.js:1:337418)
[7/28/2023 10:32:56 PM]: Load event: settings.html (at preload.js:1:337418)
[7/28/2023 10:36:55 PM]: Load event: index.html (at preload.js:1:337418)
[7/28/2023 10:36:57 PM]: Load event: apps.html (at preload.js:1:337418)
[7/28/2023 10:36:57 PM]: Load event: apps.html (at preload.js:1:337418)

[7/28/2023 10:36:57 PM]: Testing internet speed, please wait... (at preload.js:1:612068)
[7/28/2023 10:36:57 PM]: Load event: apps.html (at preload.js:1:337418)

[7/28/2023 10:36:57 PM]: Testing internet speed, please wait... (at preload.js:1:612068)

[7/28/2023 10:36:59 PM]: Internet speed is 14.06 Mbps (at preload.js:1:611044)
[7/28/2023 10:36:57 PM]: Load event: apps.html (at preload.js:1:337418)

[7/28/2023 10:36:57 PM]: Testing internet speed, please wait... (at preload.js:1:612068)

[7/28/2023 10:36:59 PM]: Internet speed is 14.06 Mbps (at preload.js:1:611044)

[7/28/2023 10:37:00 PM]: Checking for updates... (at preload.js:1:810623)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
[7/28/2023 10:38:40 PM]: Error: Timeout reached
    at C:\Users\faheemy\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:808619 (at preload.js:1:936343)
[8/5/2023 11:36:44 AM]: Load event: index.html (at preload.js:1:337418)
[8/5/2023 11:37:23 AM]: Load event: settings.html (at preload.js:1:337418)

**Comment by KK-Designs** [comment]
Should be fixed in the latest release 👍
