### ISSUE TITLE
HP EliteDesh 800 G2

### ISSUE THREAD

**Issue by dh-orko** [KK-Designs/UpdateHub#168]
```
TypeError: Invalid badgeNumber specified.
Expected: number
Got: object
    at Badge.update (C:\Users\aatra\AppData\Local\Programs\update-hub\resources\app.asar\node_modules\electron-taskbar-badge\lib\cjs\index.js:66:10)
    at SystemPreferences.<anonymous> (C:\Users\aatra\AppData\Local\Programs\update-hub\resources\app.asar\node_modules\electron-taskbar-badge\lib\cjs\index.js:50:9)
    at SystemPreferences.emit (node:events:513:28)
```

---

update-hub 2.1.0
Electron 25.3.1
win32 10.0.19045
Locale: en-US

**Comment by KK-Designs** [comment]
Should be fixed in the latest release 👍
