### ISSUE TITLE
Error after wake up

### ISSUE THREAD

**Issue by Corsair-63** [KK-Designs/UpdateHub#196]
```
TypeError: Invalid badgeNumber specified.
Expected: number
Got: object
    at Badge.update (C:\Users\corsa\AppData\Local\Programs\update-hub\resources\app.asar\node_modules\electron-taskbar-badge\lib\cjs\index.js:66:10)
    at SystemPreferences.<anonymous> (C:\Users\corsa\AppData\Local\Programs\update-hub\resources\app.asar\node_modules\electron-taskbar-badge\lib\cjs\index.js:50:9)
    at SystemPreferences.emit (node:events:513:28)
```

---

update-hub 2.1.0
Electron 25.3.1
win32 10.0.22621
Locale: en-US

**Comment by KK-Designs** [comment]
The issue has been resolved in the latest version of UpdateHub. Closing as it is already fixed.
