### ISSUE TITLE
Getting the error ```TypeError: Cannot read properties of undefined (reading 'replace')```

### ISSUE THREAD

**Issue by ded45206** [KK-Designs/UpdateHub#222]
Getting the error ```TypeError: Cannot read properties of undefined (reading 'replace')
    at escapeRegExp (C:\Users\DED2013\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:119387)
    at C:\Users\DED2013\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:570892
    at Array.filter (<anonymous>)
    at FSWatcher.<anonymous> (C:\Users\DED2013\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:570869)
    at FSWatcher.emit (node:events:513:28)
    at FSEvent.onchange (node:internal/fs/watchers:215:12)```.

**Comment by KK-Designs** [comment]
What are you doing thats causing this issue?
