### ISSUE TITLE
Starts up and stays on "loading" forever.

### ISSUE THREAD

**Issue by baettigp** [KK-Designs/UpdateHub#271]
Hi
The Updatehub starts up and stays on "loading" forever, no program is found.
Same happens if started as "administrator"

Edition	Windows 10 Pro
Version	22H2
Installiert am	‎11.‎01.‎2023
Betriebssystembuild	19045.3448
Leistung	Windows Feature Experience Pack 1000.19044.1000.0

![grafik](https://github.com/KK-Designs/UpdateHub/assets/135322/58bf5f3f-3a8c-471b-a9d4-b2dd02624580)

![grafik](https://github.com/KK-Designs/UpdateHub/assets/135322/f1929f04-f610-464f-a5d2-e8b8aceb5028)

**Comment by antisocialian** [comment]
getting the same on Windows 11 Pro
version 23h2
build 22631.2338
experience Windows Feature Experience Pack 1000.22674.1000.0

also to note, it isn't drawing the titlebar so the window can't be moved or closed via that (but alt+space still brings up the window menu to allow for moving that way. alt+space, 'm'ove, press a cursor(arrow) key and then move mouse, click to finish the move)

checking the console(ctrl+shift+i, console) it shows:

```
Uncaught (in promise) Error: Command failed: winget --info
The system cannot execute the specified program.
    at __node_internal_genericNodeError (VM12 errors:867:15)
    at checkExecSyncError (VM284 node:child_process:911:11)
    at Object.execSync (VM284 node:child_process:983:15)
    at Object.execSync (VM158 asar_bundle:2:12758)
    at sendErrorLogs (VM164 C:\Users\antis\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:114716)
    at Object.kRnsD (VM164 C:\Users\antis\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:956372)
    at VM164 C:\Users\antis\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:956529
    at Object.<anonymous> (VM164 C:\Users\antis\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:956861)
    at Object.<anonymous> (VM164 C:\Users\antis\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:2:3)
    at Module._compile (VM126 loader:1271:14)
```

attempting to run the command `winget --info` in a cmd window shows it isn't a valid application, in powershell it shows `Program 'winget.exe' failed to run: The process has no package identityAt line:1 char:1`

i tried installing the winget-cli from the microsoft github, but it's already installed and a repair shows no change. I figure it's something to do with winget, but i haven't had enough coffee to figure that part out yet.

**Comment by baettigp** [comment]
Hmm I also tried installing winget but it wasn't happy about that.

`VM1536 errors:867 Uncaught (in promise) Error: Command failed: winget --info
Der Befehl "winget" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

    at __node_internal_genericNodeError (VM1536 errors:867:15)
    at checkExecSyncError (VM1705 node:child_process:911:11)
    at Object.execSync (VM1705 node:child_process:983:15)
    at Object.execSync (VM1682 asar_bundle:2:12758)
    at sendErrorLogs (VM164 C:\Users\bap\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:114716)
    at Object.kRnsD (VM164 C:\Users\bap\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:956372)
    at VM164 C:\Users\bap\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:956529
    at Object.<anonymous> (VM164 C:\Users\bap\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:956861)
    at Object.<anonymous> (VM164 C:\Users\bap\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:2:3)
    at Module._compile (VM1650 loader:1271:14)
donate-sdk.js:1 DonateButtonManager props  Object
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/types.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/load.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/options.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/static.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/stringify.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/decode.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/decode-data-html.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/decode-data-xml.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/decode_codepoint.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/encode.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/encode-html.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/escape.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/traversal.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/manipulation.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/querying.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/legacy.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/helpers.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/feeds.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/cheerio.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/attributes.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/utils.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/traversing.js.map: Unexpected end of JSON input
2DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/compile.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/sort.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/general.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/attributes.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/filters.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/parse.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/compile.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/pseudos.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/aliases.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/subselects.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/helpers.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/positionals.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/manipulation.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/parse.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/css.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/forms.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/parse5-adapter.js.map: Unexpected end of JSON input
3DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/preprocessor.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/unicode.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/error-codes.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/token.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/html.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/open-element-stack.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/formatting-element-list.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/default.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/doctype.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/foreign-content.js.map: Unexpected end of JSON input
3DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/Parser.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/Tokenizer.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/pages/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/bap/AppData/Local/Programs/update-hub/resources/app.asar/assets/js/donate-sdk.js.map: Unexpected end of JSON input`

Console Output

**Comment by KK-Designs** [comment]
[v2.3.0](https://github.com/NexovaDev/UpdateHub/releases/tag/v2.3.0) Should bring a popup saying that WinGet couldn't be loaded without crashing the whole app. If WinGet is still broken try uninstalling/reinstalling it
