### ISSUE TITLE
Getting the error ```Error: Timeout reached```

### ISSUE THREAD

**Issue by ogiordanogo** [KK-Designs/UpdateHub#87]
Getting the error ```Error: Timeout reached
    at C:\Users\ogior\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:815325```.

Hello I have this error message on a Windows 10. I have try to make a left click and execute "Execute with Admintrator" but I have the same error message. Only update windows store and udate windows work.
![image](https://github.com/KK-Designs/UpdateHub/assets/59175420/77777d12-4a05-42af-b063-24bafd5f7557)

```
TypeError: Invalid badgeNumber specified.
Expected: number
Got: object
    at Badge.update (C:\Users\ogior\AppData\Local\Programs\update-hub\resources\app.asar\node_modules\electron-taskbar-badge\lib\cjs\index.js:66:10)
    at SystemPreferences.<anonymous> (C:\Users\ogior\AppData\Local\Programs\update-hub\resources\app.asar\node_modules\electron-taskbar-badge\lib\cjs\index.js:50:9)
    at SystemPreferences.emit (node:events:513:28)
```

---

update-hub 2.0.0
Electron 25.3.0
win32 10.0.19045
Locale: en-US

**Comment by KK-Designs** [comment]
We fixed the `TypeError: Invalid badgeNumber specified.` and the timeout error. Update and try again
